import type { Metadata } from 'next'
import Link from 'next/link'
import Header from '@/components/landing/Header'
import Footer from '@/components/landing/Footer'

export const metadata: Metadata = {
  title: 'Glossary of Legislative & Financial Terms',
  description: 'Comprehensive glossary of legislative and financial terms used in Congressional activity tracking. Understand bills, impact scores, market sentiment, federal contracts, and more.',
  alternates: { canonical: 'https://hillsignal.com/glossary' },
}

const TERMS: { term: string; definition: string; category: string }[] = [
  // Legislative Terms
  { term: 'Bill', definition: 'A proposed law introduced in Congress. Bills are designated as H.R. (House of Representatives) or S. (Senate), followed by a number. A bill must pass both chambers and be signed by the President to become law.', category: 'Legislative' },
  { term: 'Resolution', definition: 'A formal expression of opinion or intent by Congress. Joint resolutions have the force of law, while simple and concurrent resolutions do not.', category: 'Legislative' },
  { term: 'Committee Action', definition: 'When a Congressional committee reviews, amends, or votes on a bill. Committee approval is typically required before a bill reaches the full chamber for a vote.', category: 'Legislative' },
  { term: 'Cloture', definition: 'A procedure to end debate in the Senate, requiring 60 votes. Often used to overcome a filibuster and move legislation to a final vote.', category: 'Legislative' },
  { term: 'Markup', definition: 'A committee session where members review and amend a bill line by line before voting to send it to the full chamber.', category: 'Legislative' },
  { term: 'Appropriations Bill', definition: 'Legislation that authorizes federal agencies to spend money. These bills determine funding levels for government programs and are a primary driver of federal contract awards.', category: 'Legislative' },
  { term: 'Authorization Bill', definition: 'Legislation that creates or continues a federal program and sets maximum funding levels. Distinct from appropriations, which provide the actual funding.', category: 'Legislative' },
  { term: 'Reconciliation', definition: 'A special budget process that allows certain tax and spending legislation to pass the Senate with a simple majority (51 votes) instead of the usual 60.', category: 'Legislative' },
  { term: 'Continuing Resolution (CR)', definition: 'Temporary legislation to fund the government at existing levels when regular appropriations bills have not been enacted by the start of the fiscal year.', category: 'Legislative' },
  { term: 'Government Shutdown', definition: 'Occurs when Congress fails to pass funding legislation, causing non-essential federal operations to cease. Can significantly impact defense contractors and government-dependent businesses.', category: 'Legislative' },

  // Financial & Market Terms
  { term: 'Impact Score', definition: 'HillSignal\'s proprietary 1-10 rating measuring the potential market impact of a Congressional signal. Scores of 7+ indicate high-impact legislation or contracts likely to move stock prices. Generated by AI analysis considering dollar amounts, sector breadth, and regulatory implications.', category: 'HillSignal' },
  { term: 'Market Sentiment', definition: 'HillSignal\'s AI-generated assessment of whether a Congressional signal is bullish (positive for stock prices), bearish (negative), or neutral. Based on analysis of the legislation\'s likely effect on affected companies and sectors.', category: 'HillSignal' },
  { term: 'Signal', definition: 'A Congressional action (bill, contract award, or legislative activity) that has been identified and analyzed by HillSignal\'s AI as having potential market impact. Each signal includes affected tickers, sectors, sentiment, and an impact score.', category: 'HillSignal' },
  { term: 'Affected Tickers', definition: 'Publicly traded stock symbols identified by HillSignal\'s AI as likely to be impacted by a specific Congressional signal. Tickers are selected based on company exposure to the relevant sector, government contracts, or regulatory environment.', category: 'HillSignal' },
  { term: 'Alternative Data', definition: 'Non-traditional data sources used for investment analysis, such as Congressional activity, satellite imagery, or social media sentiment. HillSignal provides alternative data from Congress.gov and USAspending.gov.', category: 'Financial' },
  { term: 'Political Intelligence', definition: 'Information about government activity that may affect financial markets. Historically available only to institutional investors and hedge funds through expensive consultants.', category: 'Financial' },
  { term: 'Federal Contract Award', definition: 'A binding agreement between the federal government and a private company to provide goods or services. Contract awards above $10M tracked by HillSignal can significantly impact the winning company\'s stock price and sector dynamics.', category: 'Financial' },
  { term: 'Sector Rotation', definition: 'An investment strategy of shifting capital between market sectors based on economic conditions. Congressional activity often drives sector rotation — e.g., a defense spending bill benefits the Defense sector.', category: 'Financial' },
  { term: 'Regulatory Risk', definition: 'The risk that a change in regulations will negatively affect a company or sector. New legislation can create or eliminate regulatory risk, impacting stock valuations.', category: 'Financial' },
  { term: 'USAspending.gov', definition: 'The official U.S. government website tracking federal spending, including contract awards. HillSignal monitors this source for new contract awards across 12 sectors.', category: 'Data Sources' },
  { term: 'Congress.gov', definition: 'The official website of the U.S. Congress providing access to legislative information including bills, resolutions, and committee activity. HillSignal\'s primary data source for legislative signals.', category: 'Data Sources' },
]

export default function GlossaryPage() {
  const categories = [...new Set(TERMS.map(t => t.category))]

  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'DefinedTermSet',
    name: 'HillSignal Glossary of Legislative & Financial Terms',
    description: 'Comprehensive glossary of terms used in Congressional activity tracking and market analysis.',
    url: 'https://hillsignal.com/glossary',
    hasDefinedTerm: TERMS.map(t => ({
      '@type': 'DefinedTerm',
      name: t.term,
      description: t.definition,
    })),
  }

  return (
    <main className="min-h-screen bg-hill-black">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <Header />
      <div className="pt-20 pb-16 max-w-4xl mx-auto px-4">
        <p className="text-hill-orange font-mono text-sm mb-2">REFERENCE</p>
        <h1 className="text-4xl font-bold text-hill-white mb-3">Glossary</h1>
        <p className="text-hill-muted text-lg mb-10 max-w-2xl">Key legislative and financial terms used on HillSignal. Understanding these concepts will help you interpret Congressional signals and their market impact.</p>

        {categories.map(cat => (
          <section key={cat} className="mb-10">
            <h2 className="text-xl font-semibold text-hill-orange mb-4 border-b border-hill-border pb-2">{cat}</h2>
            <dl className="space-y-4">
              {TERMS.filter(t => t.category === cat).map(t => (
                <div key={t.term} className="bg-hill-dark border border-hill-border rounded-lg p-4">
                  <dt className="text-hill-white font-semibold text-base mb-1">{t.term}</dt>
                  <dd className="text-hill-muted text-sm leading-relaxed">{t.definition}</dd>
                </div>
              ))}
            </dl>
          </section>
        ))}

        <div className="mt-12 text-center bg-hill-dark border border-hill-border rounded-lg p-8">
          <h2 className="text-2xl font-bold text-hill-white mb-2">Ready to Use These Insights?</h2>
          <p className="text-hill-muted mb-4">See Congressional signals analyzed in real terms you understand.</p>
          <Link href="/signup" className="inline-block bg-hill-orange text-black font-semibold px-6 py-3 rounded-lg hover:bg-hill-orange/90 transition-colors">
            Become a Member →
          </Link>
        </div>
      </div>
      <Footer />
    </main>
  )
}
